model_provider = "gemini"
model = "mart-coder"
model_reasoning_effort = "high"
disable_response_storage = true

[model_providers.custom]
name = "custom"
wire_api = "responses"
requires_openai_auth = false  # 👈 1. 这里改为 false，交由 cc-switch 本地直接处理 Key 的传递
base_url = "https://9router.234124123.xyz/v1"

[model_providers.gemini]
name = "gemini"
base_url = "http://127.0.0.1:15721/v1" # 👈 2. 确保端口与你 cc-switch 路由页面的 15721 一致
wire_api = "responses"
experimental_bearer_token = "PROXY_MANAGED"

[marketplaces.openai-bundled]
last_updated = "2026-06-05T15:17:30Z"
source_type = "local"
source = '\\?\C:\Users\lzhumy\.codex\.tmp\bundled-marketplaces\openai-bundled'