export type BookTrainingMode = 'one_minute_retell' | 'concept_explanation';
export type BookExerciseStatus = 'ready' | 'running' | 'succeeded' | 'failed' | 'cancelled';
export type BookExerciseDimension = { score: number; feedback: string; evidenceIds: string[] };
export type BookExercise = { id: string; bookId: string; frameworkRevisionId: string; frameworkNodeId: string; trainingMode: BookTrainingMode; prompt: string; goals: string[]; evidence: Array<{ id: string; quote: string; locator: Record<string, unknown> }>; status: BookExerciseStatus; taskId?: string; rawTranscript?: string; polishedTranscript?: string; revisedTranscript?: string; viewedEvidence?: boolean; evaluation?: { totalScore: number; dimensions: Record<string, BookExerciseDimension>; summary: string; omissions: string[]; misconceptions: string[]; recommendedStructure: string[]; exemplar: string }; errorCode?: string; terminal?: boolean };
const request = async <T>(path: string, init?: RequestInit): Promise<T> => { const response = await fetch(path, { credentials: 'include', ...init, headers: { ...(init?.body && !(init.body instanceof FormData) ? { 'Content-Type': 'application/json' } : {}), ...init?.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw Object.assign(new Error(body.error || `HTTP ${response.status}`), { errorCode: body.errorCode }); return body; };
const base = (bookId: string, revisionId: string, nodeId: string) => `/api/books/${encodeURIComponent(bookId)}/frameworks/${encodeURIComponent(revisionId)}/nodes/${encodeURIComponent(nodeId)}/exercises`;
export const createBookExercise = async (bookId: string, revisionId: string, nodeId: string, trainingMode: BookTrainingMode) => (await request<{ exercise: BookExercise }>(base(bookId, revisionId, nodeId), { method: 'POST', body: JSON.stringify({ trainingMode }) })).exercise;
export const transcribeBookExerciseAudio = async (bookId: string, audio: Blob) => { const form = new FormData(); form.append('file', audio, 'exercise.webm'); return request<{ rawTranscript: string; polishedTranscript: string }>(`/api/books/${encodeURIComponent(bookId)}/exercises/transcriptions`, { method: 'POST', body: form }); };
export const evaluateBookExercise = async (bookId: string, revisionId: string, nodeId: string, exerciseId: string, payload: { taskId: string; rawTranscript: string; polishedTranscript?: string; revisedTranscript?: string; useRevisedTranscript?: boolean; durationSeconds: number; viewedEvidence?: boolean }) => request<{ taskId: string; status: BookExerciseStatus; createdAt: number }>(`${base(bookId, revisionId, nodeId)}/${encodeURIComponent(exerciseId)}/evaluate`, { method: 'POST', body: JSON.stringify(payload) });
export const getBookExercise = async (bookId: string, revisionId: string, nodeId: string, exerciseId: string, signal?: AbortSignal) => (await request<{ exercise: BookExercise }>(`${base(bookId, revisionId, nodeId)}/${encodeURIComponent(exerciseId)}`, { signal })).exercise;
export const cancelBookExerciseEvaluation = async (bookId: string, revisionId: string, nodeId: string, exerciseId: string) => (await request<{ exercise: BookExercise }>(`${base(bookId, revisionId, nodeId)}/${encodeURIComponent(exerciseId)}/evaluate/cancel`, { method: 'POST' })).exercise;
export const listBookExercises = async (bookId: string) => (await request<{ exercises: BookExercise[] }>(`/api/books/${encodeURIComponent(bookId)}/exercises`)).exercises;
const abortError = () => new DOMException('Polling aborted', 'AbortError');
export async function pollBookExercise(bookId: string, revisionId: string, nodeId: string, exerciseId: string, { intervalMs = 1500, maxAttempts = 200, maxDurationMs = 300_000, signal }: { intervalMs?: number; maxAttempts?: number; maxDurationMs?: number; signal?: AbortSignal } = {}) { const started = Date.now(); for (let attempt = 0; attempt < maxAttempts; attempt++) { if (signal?.aborted) throw abortError(); const exercise = await getBookExercise(bookId, revisionId, nodeId, exerciseId, signal); if (['succeeded', 'failed', 'cancelled'].includes(exercise.status)) return exercise; if (Date.now() - started >= maxDurationMs || attempt === maxAttempts - 1) throw Object.assign(new Error('评价状态轮询超时'), { errorCode: 'POLL_TIMEOUT' }); await new Promise<void>((resolve, reject) => { const timer = setTimeout(resolve, intervalMs); signal?.addEventListener('abort', () => { clearTimeout(timer); reject(abortError()); }, { once: true }); }); } throw Object.assign(new Error('评价状态轮询超时'), { errorCode: 'POLL_TIMEOUT' }); }
