const crypto = require('node:crypto');
const MODES = new Set(['one_minute_retell', 'concept_explanation']);
const TERMINAL = new Set(['succeeded', 'failed', 'cancelled']);
const DIMENSIONS = { one_minute_retell: ['theoryAccuracy','coverage','structure','clarity','durationControl'], concept_explanation: ['definitionAccuracy','coreMechanism','exampleQuality','boundaryCounterexample','plainClarity'] };
function failure(errorCode,message){return Object.assign(new Error(message),{errorCode});}
function parse(value,fallback={}){try{return JSON.parse(value);}catch{return fallback;}}
function tx(db,work){if(db.transaction)return db.transaction(work)();db.exec('BEGIN IMMEDIATE');try{const result=work();db.exec('COMMIT');return result;}catch(error){db.exec('ROLLBACK');throw error;}}
function createBookExerciseService(db,{evaluate,transcribe,leaseMs=60_000,heavyGate,maxAttempts=3,baseBackoffMs=1000}={}){
  if(typeof evaluate!=='function')evaluate=async()=>{throw failure('EVALUATION_FAILED','evaluation is not configured');};
  const ownedNode=({bookId,ownerId,revisionId,nodeId})=>db.prepare(`SELECT f.*,n.id node_id,n.title node_title,n.summary FROM books b JOIN framework_revisions f ON f.book_id=b.id JOIN framework_nodes n ON n.framework_revision_id=f.id WHERE b.id=? AND b.owner_id=? AND b.deleted_at IS NULL AND f.id=? AND f.status='confirmed' AND n.id=? AND n.status='confirmed'`).get(bookId,ownerId,revisionId,nodeId);
  const evidence=nodeId=>db.prepare('SELECT id,quote,locator_json FROM knowledge_evidence WHERE framework_node_id=? AND is_valid=1 ORDER BY created_at').all(nodeId).map(r=>({id:r.id,quote:r.quote,locator:parse(r.locator_json)}));
  const findOwned=a=>db.prepare('SELECT e.* FROM book_exercises e JOIN books b ON b.id=e.book_id WHERE e.id=? AND e.book_id=? AND e.owner_id=? AND e.framework_revision_id=? AND e.framework_node_id=? AND b.deleted_at IS NULL AND b.retrieval_disabled=0').get(a.exerciseId,a.bookId,a.ownerId,a.revisionId,a.nodeId);
  const present=r=>r&&({id:r.id,bookId:r.book_id,frameworkRevisionId:r.framework_revision_id,frameworkNodeId:r.framework_node_id,trainingMode:r.training_mode,prompt:r.prompt,goals:parse(r.goals_json,[]),evidence:parse(r.evidence_json,[]),status:r.status,taskId:r.task_id,rawTranscript:r.raw_transcript,polishedTranscript:r.polished_transcript,revisedTranscript:r.revised_transcript,viewedEvidence:!!r.viewed_evidence,evaluation:r.evaluation_json?parse(r.evaluation_json):null,errorCode:r.error_code,durationSeconds:r.duration_seconds,createdAt:r.created_at,updatedAt:r.updated_at,terminal:TERMINAL.has(r.status)});
  function create({bookId,ownerId,revisionId,nodeId,trainingMode}){if(!MODES.has(trainingMode))throw failure('VALIDATION_ERROR','unsupported training mode');const node=ownedNode({bookId,ownerId,revisionId,nodeId});if(!node)throw failure('NOT_FOUND','framework node not found');const links=evidence(nodeId);if(!links.length)throw failure('VALIDATION_ERROR','node has no valid evidence');const retell=trainingMode==='one_minute_retell',prompt=retell?`请在60秒内，不照读原文，复述“${node.node_title}”的定义、关键机制和结论。`:`请在60秒内，用通俗语言解释“${node.node_title}”，并给出一个例子。`,goals=retell?['准确说明理论定义','覆盖关键机制与结论','结构完整、表达清晰']:['准确解释定义与机制','给出恰当例子','说明边界或反例'],id=crypto.randomUUID(),now=Date.now();db.prepare(`INSERT INTO book_exercises(id,book_id,owner_id,framework_revision_id,framework_node_id,training_mode,prompt,goals_json,evidence_json,status,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?,'ready',?,?)`).run(id,bookId,ownerId,revisionId,nodeId,trainingMode,prompt,JSON.stringify(goals),JSON.stringify(links),now,now);return present(db.prepare('SELECT * FROM book_exercises WHERE id=?').get(id));}
  function submit({bookId,ownerId,revisionId,nodeId,exerciseId,rawTranscript,polishedTranscript='',revisedTranscript='',useRevisedTranscript=false,durationSeconds,viewedEvidence=false}){const exercise=findOwned({bookId,ownerId,revisionId,nodeId,exerciseId});if(!exercise)throw failure('NOT_FOUND','exercise not found');if(!Number.isFinite(durationSeconds)||durationSeconds<1||durationSeconds>60)throw failure('VALIDATION_ERROR','duration must be between 1 and 60 seconds');const raw=String(rawTranscript||'').trim(),revised=useRevisedTranscript?String(revisedTranscript||'').trim():'';if(!raw||useRevisedTranscript&&!revised)throw failure('TRANSCRIPTION_EMPTY','transcription is empty');return tx(db,()=>{const existing=db.prepare('SELECT * FROM book_exercise_tasks WHERE exercise_id=?').get(exerciseId);if(existing)return existing;const id=crypto.randomUUID(),now=Date.now(),input={trainingMode:exercise.training_mode,rawTranscript:raw,revisedTranscript:revised||null,scoringTranscript:revised||raw,node:db.prepare('SELECT title,summary FROM framework_nodes WHERE id=?').get(nodeId),evidence:parse(exercise.evidence_json,[]),durationSeconds};db.prepare(`INSERT INTO book_exercise_tasks(id,exercise_id,book_id,owner_id,status,lease_token,input_json,attempt_count,created_at,updated_at)VALUES(?,?,?,?,'pending','',?,0,?,?)`).run(id,exerciseId,bookId,ownerId,JSON.stringify(input),now,now);db.prepare("UPDATE book_exercises SET status='running',task_id=?,raw_transcript=?,polished_transcript=?,revised_transcript=?,duration_seconds=?,viewed_evidence=?,updated_at=? WHERE id=?").run(id,raw,String(polishedTranscript||''),revised||null,durationSeconds,viewedEvidence?1:0,now,exerciseId);return db.prepare('SELECT * FROM book_exercise_tasks WHERE id=?').get(id);});}
  function claimNext({now=Date.now()}={}){return tx(db,()=>{const row=db.prepare("SELECT id FROM book_exercise_tasks WHERE status IN ('pending','retrying') AND (next_attempt_at IS NULL OR next_attempt_at<=?) ORDER BY created_at LIMIT 1").get(now);if(!row)return null;const token=crypto.randomUUID();const changed=db.prepare("UPDATE book_exercise_tasks SET status='running',lease_token=?,lease_expires_at=?,heartbeat_at=?,attempt_count=attempt_count+1,updated_at=? WHERE id=? AND status IN ('pending','retrying')").run(token,now+leaseMs,now,now,row.id).changes;return changed?{...db.prepare('SELECT * FROM book_exercise_tasks WHERE id=?').get(row.id),leaseToken:token}:null;});}
  function heartbeat(id,token,{now=Date.now()}={}){return db.prepare("UPDATE book_exercise_tasks SET heartbeat_at=?,lease_expires_at=?,updated_at=? WHERE id=? AND status='running' AND lease_token=? AND lease_expires_at>=? AND cancel_requested_at IS NULL").run(now,now+leaseMs,now,id,token,now).changes===1;}
  function recoverExpired({now=Date.now()}={}){return db.prepare("UPDATE book_exercise_tasks SET status='retrying',lease_token='',lease_expires_at=NULL,next_attempt_at=? WHERE status='running' AND lease_expires_at IS NOT NULL AND lease_expires_at<?").run(now,now).changes;}
  function recoverLegacyRunning({now=Date.now()}={}){db.exec('CREATE TABLE IF NOT EXISTS book_migrations(name TEXT PRIMARY KEY,applied_at INTEGER NOT NULL)');return tx(db,()=>{if(db.prepare("SELECT 1 FROM book_migrations WHERE name='exercise_running_requires_lease'").get())return 0;const rows=db.prepare("SELECT id,exercise_id FROM book_exercise_tasks WHERE status='running' AND lease_expires_at IS NULL").all();for(const row of rows){db.prepare("UPDATE book_exercise_tasks SET status='retrying',lease_token='',next_attempt_at=?,updated_at=? WHERE id=?").run(now,now,row.id);db.prepare("UPDATE book_exercises SET status='running',updated_at=? WHERE id=? AND status NOT IN ('succeeded','failed','cancelled')").run(now,row.exercise_id);}db.prepare('INSERT INTO book_migrations(name,applied_at) VALUES(?,?)').run('exercise_running_requires_lease',now);return rows.length;});}
  function validate(mode,result,allowedEvidence){if(!result||!Number.isFinite(result.totalScore)||!result.dimensions||typeof result.summary!=='string'||!Array.isArray(result.omissions)||!Array.isArray(result.misconceptions)||!Array.isArray(result.recommendedStructure)||typeof result.exemplar!=='string')throw failure('EVALUATION_FAILED','evaluation schema invalid');const keys=Object.keys(result.dimensions);if(keys.length!==DIMENSIONS[mode].length||keys.some(k=>!DIMENSIONS[mode].includes(k)))throw failure('EVALUATION_FAILED','evaluation dimensions invalid');for(const key of keys){const item=result.dimensions[key];if(!item||!Number.isFinite(item.score)||item.score<0||item.score>100||!Array.isArray(item.evidenceIds)||item.evidenceIds.some(id=>!allowedEvidence.has(id))||typeof item.feedback!=='string')throw failure('EVALUATION_FAILED','evaluation evidence invalid');}return result;}
  function ensureSession(ownerId,now){const date=new Date(now).toISOString().slice(0,10),found=db.prepare('SELECT id FROM training_sessions WHERE user_id=? AND training_date=?').get(ownerId,date);if(found)return found;const id=crypto.randomUUID();db.prepare(`INSERT INTO training_sessions(id,user_id,training_date,total_minutes,listen_minutes,logic_minutes,extra_json,created_at,updated_at)VALUES(?,?,?,0,0,0,'{}',?,?)`).run(id,ownerId,date,now,now);return{id};}
  function completeTask({taskId,leaseToken,evaluation}){const task=db.prepare("SELECT * FROM book_exercise_tasks WHERE id=? AND status='running' AND lease_token=? AND lease_expires_at>=? AND cancel_requested_at IS NULL").get(taskId,leaseToken,Date.now());if(!task)return false;const input=parse(task.input_json),result=validate(input.trainingMode,evaluation,new Set(input.evidence.map(e=>e.id))),exercise=db.prepare('SELECT * FROM book_exercises WHERE id=?').get(task.exercise_id),now=Date.now();return tx(db,()=>{if(!db.prepare("UPDATE book_exercise_tasks SET status='succeeded',finished_at=?,updated_at=? WHERE id=? AND status='running' AND lease_token=? AND lease_expires_at>=? AND cancel_requested_at IS NULL").run(now,now,taskId,leaseToken,now).changes)return false;const session=ensureSession(exercise.owner_id,now),answer={bookId:exercise.book_id,frameworkRevisionId:exercise.framework_revision_id,frameworkNodeId:exercise.framework_node_id,trainingMode:exercise.training_mode,rawTranscript:input.rawTranscript,revisedTranscript:input.revisedTranscript,evaluation:result,taskId,viewedEvidence:!!exercise.viewed_evidence};db.prepare(`INSERT OR IGNORE INTO training_attempts(id,session_id,user_id,module_type,scene_type,case_text,user_answer,duration_seconds,score,created_at)VALUES(?,?,?,?,?,?,?,?,?,?)`).run(crypto.randomUUID(),session.id,exercise.owner_id,'oral',exercise.training_mode,exercise.prompt,JSON.stringify(answer),input.durationSeconds,result.totalScore,now);db.prepare("UPDATE book_exercises SET status='succeeded',evaluation_json=?,error_code=NULL,updated_at=? WHERE id=? AND task_id=?").run(JSON.stringify(result),now,exercise.id,taskId);return true;});}
  async function runOnce({now=Date.now()}={}){const task=claimNext({now});if(!task)return false;const input=parse(task.input_json),work=()=>evaluate(input),pulse=setInterval(()=>heartbeat(task.id,task.leaseToken),Math.max(1000,Math.floor(leaseMs/3)));try{const result=await(heavyGate?heavyGate.run(work):work());if(!completeTask({taskId:task.id,leaseToken:task.leaseToken,evaluation:result}))return true;}catch(error){const finishedAt=now,attempt=Number(task.attempt_count||0),retryable=!!error.retryable&&attempt<maxAttempts,nextAttemptAt=retryable?now+baseBackoffMs*(2**(attempt-1)):null;db.prepare("UPDATE book_exercise_tasks SET status=?,error_code='EVALUATION_FAILED',lease_token='',lease_expires_at=NULL,next_attempt_at=?,finished_at=?,updated_at=? WHERE id=? AND status='running' AND lease_token=?").run(retryable?'retrying':'failed',nextAttemptAt,retryable?null:finishedAt,finishedAt,task.id,task.leaseToken);if(!retryable)db.prepare("UPDATE book_exercises SET status='failed',error_code='EVALUATION_FAILED',updated_at=? WHERE id=? AND task_id=? AND status='running'").run(finishedAt,task.exercise_id,task.id);}finally{clearInterval(pulse);}return true;}
  function cancel(args){const exercise=findOwned(args);if(!exercise)throw failure('NOT_FOUND','exercise not found');const now=Date.now();tx(db,()=>{db.prepare("UPDATE book_exercise_tasks SET status='cancelled',cancel_requested_at=?,finished_at=?,lease_token='',lease_expires_at=NULL,updated_at=? WHERE exercise_id=? AND status IN ('pending','retrying','running')").run(now,now,now,args.exerciseId);db.prepare("UPDATE book_exercises SET status='cancelled',updated_at=? WHERE id=? AND status='running'").run(now,args.exerciseId);});return present(db.prepare('SELECT * FROM book_exercises WHERE id=?').get(args.exerciseId));}
  function get(args){const row=findOwned(args);if(!row)throw failure('NOT_FOUND','exercise not found');return present(row);}function list({bookId,ownerId}){if(!db.prepare('SELECT 1 FROM books WHERE id=? AND owner_id=?').get(bookId,ownerId))throw failure('NOT_FOUND','book not found');return db.prepare('SELECT * FROM book_exercises WHERE book_id=? AND owner_id=? ORDER BY created_at DESC').all(bookId,ownerId).map(present);}async function transcribeAudio(file,ownerId){const r=await transcribe(file,ownerId),rawTranscript=String(r?.rawTranscript||'').trim();if(!rawTranscript)throw failure('TRANSCRIPTION_EMPTY','transcription is empty');return{rawTranscript,polishedTranscript:String(r?.polishedTranscript||rawTranscript).trim()};}
  return{create,submit,get,list,cancel,claimNext,heartbeat,recoverExpired,recoverLegacyRunning,completeTask,runOnce,transcribeAudio};
}
module.exports={createBookExerciseService,MODES,TERMINAL};
