const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const { createBookJobService } = require('./bookJobService');

function failure(errorCode, message) { return Object.assign(new Error(message), { errorCode }); }
function parse(value, fallback = {}) { try { return JSON.parse(value); } catch { return fallback; } }
function hash(value) { return crypto.createHash('sha256').update(value).digest('hex'); }
function normalized(value) { return value.normalize('NFKC').replace(/\s+/g, ''); }
function transaction(db, work) { if (db.transaction) return db.transaction(work)(); db.exec('BEGIN IMMEDIATE'); try { const result = work(); db.exec('COMMIT'); return result; } catch (error) { db.exec('ROLLBACK'); throw error; } }
function locatorUnit(locator) { return Number.isInteger(locator?.unitIndex) ? locator.unitIndex : Number.isInteger(locator?.pageIndex) ? locator.pageIndex : null; }
function charRange(locator, text) {
  if (Number.isInteger(locator?.charStart) && Number.isInteger(locator?.charEnd)) return [locator.charStart, locator.charEnd];
  if (Number.isInteger(locator?.char)) return [locator.char, locator.char];
  if (locator?.kind === 'page') return [0, Math.max(0, text.length - 1)];
  return null;
}
function locateNormalized(slice, quote) {
  const target = normalized(quote); if (!target) return null;
  for (let start = 0; start < slice.length; start++) for (let end = start; end < slice.length; end++) {
    if (normalized(slice.slice(start, end + 1)) === target) return [start, end];
    if (normalized(slice.slice(start, end + 1)).length > target.length) break;
  }
  return null;
}

function createBookFrameworkService(db, { workflow, outputRoot = path.join(__dirname, '..', 'private', 'books', 'framework-steps'), jobService } = {}) {
  const jobs = jobService || createBookJobService(db);
  const ownedBook = (bookId, ownerId) => db.prepare("SELECT * FROM books WHERE id=? AND owner_id=? AND deleted_at IS NULL AND status<>'staged'").get(bookId, ownerId);
  const ownedRevision = (bookId, ownerId, revisionId) => db.prepare(`SELECT f.* FROM framework_revisions f JOIN books b ON b.id=f.book_id WHERE f.id=? AND f.book_id=? AND b.owner_id=? AND b.deleted_at IS NULL`).get(revisionId, bookId, ownerId);
  const assertDraft = (revision) => { if (revision.status !== 'draft') throw failure('INVALID_STATE', 'framework revision is immutable'); };

  function validateEvidence({ bookRevisionId, sourceUnitId, locator, quote, chapter = null }) {
    const unit = db.prepare("SELECT * FROM book_source_units WHERE id=? AND book_revision_id=? AND status='completed'").get(sourceUnitId, bookRevisionId);
    const revision = db.prepare('SELECT detected_format FROM book_revisions WHERE id=?').get(bookRevisionId);
    if (!unit || !revision || !locator || typeof quote !== 'string') throw failure('EVIDENCE_INVALID', 'evidence locator invalid');
    const unitIndex = locatorUnit(locator);
    if (unitIndex !== null && unitIndex !== unit.unit_index) throw failure('EVIDENCE_INVALID', 'evidence unit mismatch');
    if (locator.resourcePath && locator.resourcePath !== unit.resource_path) throw failure('EVIDENCE_INVALID', 'evidence resource mismatch');
    const source = fs.readFileSync(unit.raw_text_path, 'utf8');
    if (chapter) {
      const start = parse(chapter.start_locator_json); const end = parse(chapter.end_locator_json); const index = unit.unit_index;
      const first = locatorUnit(start), last = locatorUnit(end); const evidenceRange = charRange(locator, source);
      const allowedStart = index === first ? (start.char ?? start.charStart ?? 0) : 0;
      const allowedEnd = index === last ? (end.char ?? end.charEnd ?? source.length - 1) : source.length - 1;
      if (index < first || index > last || !evidenceRange || evidenceRange[0] < allowedStart || evidenceRange[1] > allowedEnd) throw failure('EVIDENCE_INVALID', 'evidence outside chapter');
      if (start.resourcePath && index === first && unit.resource_path !== start.resourcePath) throw failure('EVIDENCE_INVALID', 'evidence outside chapter resource');
      if (end.resourcePath && index === last && unit.resource_path !== end.resourcePath) throw failure('EVIDENCE_INVALID', 'evidence outside chapter resource');
    }
    const range = charRange(locator, source);
    if (!range || range[0] < 0 || range[1] < range[0] || range[1] >= source.length) throw failure('EVIDENCE_INVALID', 'evidence locator invalid');
    const slice = source.slice(range[0], range[1] + 1); let relativeStart = slice.indexOf(quote); let relativeEnd = relativeStart + quote.length - 1;
    if (relativeStart < 0) { const match = locateNormalized(slice, quote); if (!match) throw failure('EVIDENCE_INVALID', 'evidence quote does not match locator'); [relativeStart, relativeEnd] = match; }
    const fixed = { ...locator, charStart: range[0] + relativeStart, charEnd: range[0] + relativeEnd };
    if (revision.detected_format === 'pdf') { if (unit.unit_type !== 'page') throw failure('EVIDENCE_INVALID', 'PDF evidence requires page unit'); fixed.kind = 'page'; fixed.pageIndex = unit.unit_index; delete fixed.page; }
    else if (['epub','mobi','azw3'].includes(revision.detected_format)) { if (!unit.resource_path || locator.resourcePath !== unit.resource_path) throw failure('EVIDENCE_INVALID', 'ebook evidence requires resourcePath'); fixed.kind = 'resource'; fixed.resourcePath = unit.resource_path; }
    else if (revision.detected_format === 'txt') { fixed.kind = 'text'; fixed.lineStart = source.slice(0, fixed.charStart).split('\n').length; fixed.lineEnd = source.slice(0, fixed.charEnd).split('\n').length; }
    return { quote: source.slice(fixed.charStart, fixed.charEnd + 1), quoteHash: hash(source.slice(fixed.charStart, fixed.charEnd + 1)), sourceTextHash: unit.raw_text_hash || hash(source), locator: fixed };
  }

  function seedDraft({ bookId, ownerId, chapterRevisionId, nodes, model = null, workflowVersion = null, promptVersion = 'book-framework-v1', runId = null, tokenCount = 0, costAmount = 0, jobId, leaseToken }) {
    const book = ownedBook(bookId, ownerId); if (!book) throw failure('NOT_FOUND', 'book not found');
    const existing = db.prepare("SELECT * FROM framework_revisions WHERE book_id=? AND chapter_revision_id=? AND status='draft' ORDER BY created_at DESC LIMIT 1").get(bookId, chapterRevisionId); if (existing) return existing;
    return transaction(db, () => { if (jobId) jobs.assertLease(jobId, leaseToken); const id = crypto.randomUUID(), now = Date.now(), number = db.prepare('SELECT count(*) n FROM framework_revisions WHERE book_id=?').get(bookId).n + 1;
      db.prepare(`INSERT INTO framework_revisions (id,book_id,book_revision_id,chapter_revision_id,revision_number,status,model,workflow_version,prompt_version,workflow_run_id,token_count,cost_amount,created_at) VALUES (?,?,?,?,?,'draft',?,?,?,?,?,?,?)`).run(id, bookId, book.active_book_revision_id, chapterRevisionId, number, model, workflowVersion, promptVersion, runId, tokenCount, costAmount, now);
      for (const node of nodes) { db.prepare(`INSERT INTO framework_nodes (id,framework_revision_id,parent_id,node_type,origin,title,summary,order_index,status,version,confidence_level,chapter_id,source_node_ids_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(node.id, id, node.parentId, node.nodeType, node.origin || (['source_claim','system_synthesis','structural','user_added'].includes(node.nodeType) ? node.nodeType : 'source_claim'), node.title, node.summary, node.order, 'draft', node.version, node.confidenceLevel || 'medium', node.chapterId || null, JSON.stringify(node.sourceNodeIds || []), now, now);
        for (const item of node.evidence || []) { const chapter = item.chapterId ? db.prepare('SELECT * FROM book_chapters WHERE id=? AND chapter_revision_id=?').get(item.chapterId, chapterRevisionId) : null; const valid = validateEvidence({ bookRevisionId: book.active_book_revision_id, sourceUnitId: item.sourceUnitId, locator: item.locator, quote: item.quote, chapter }); db.prepare(`INSERT INTO knowledge_evidence (id,framework_node_id,book_revision_id,chapter_id,source_unit_id,locator_json,quote,quote_hash,source_text_hash,is_valid,created_at) VALUES (?,?,?,?,?,?,?,?,?,1,?)`).run(crypto.randomUUID(), node.id, book.active_book_revision_id, item.chapterId || null, item.sourceUnitId, JSON.stringify(valid.locator), valid.quote, valid.quoteHash, valid.sourceTextHash, now); }
      } return db.prepare('SELECT * FROM framework_revisions WHERE id=?').get(id); });
  }

  function list({ bookId, ownerId }) { if (!ownedBook(bookId, ownerId)) throw failure('NOT_FOUND', 'book not found'); return db.prepare('SELECT * FROM framework_revisions WHERE book_id=? ORDER BY revision_number DESC').all(bookId); }
  function detail({ bookId, ownerId, revisionId }) { const revision = ownedRevision(bookId, ownerId, revisionId); if (!revision) throw failure('NOT_FOUND', 'framework not found'); return { revision, nodes: db.prepare('SELECT * FROM framework_nodes WHERE framework_revision_id=? ORDER BY order_index').all(revisionId) }; }
  function updateNode({ bookId, ownerId, revisionId, nodeId, patch }) { const revision=ownedRevision(bookId,ownerId,revisionId);if(!revision)throw failure('NOT_FOUND','framework not found');assertDraft(revision);const node=db.prepare('SELECT * FROM framework_nodes WHERE id=? AND framework_revision_id=?').get(nodeId,revisionId);if(!node)throw failure('NOT_FOUND','node not found');const title=patch.title===undefined?node.title:String(patch.title).trim(),summary=patch.summary===undefined?node.summary:String(patch.summary);if(!title)throw failure('VALIDATION_ERROR','title required');db.prepare('UPDATE framework_nodes SET title=?,summary=?,version=version+1,updated_at=? WHERE id=?').run(title,summary,Date.now(),nodeId);return db.prepare('SELECT * FROM framework_nodes WHERE id=?').get(nodeId); }
  function merge({bookId,ownerId,revisionId,targetNodeId,sourceNodeIds}){const revision=ownedRevision(bookId,ownerId,revisionId);if(!revision)throw failure('NOT_FOUND','framework not found');assertDraft(revision);if(!db.prepare('SELECT 1 FROM framework_nodes WHERE id=? AND framework_revision_id=?').get(targetNodeId,revisionId)||!Array.isArray(sourceNodeIds)||!sourceNodeIds.length)throw failure('VALIDATION_ERROR','merge invalid');return transaction(db,()=>{for(const sourceId of sourceNodeIds.filter(id=>id!==targetNodeId)){if(!db.prepare('SELECT 1 FROM framework_nodes WHERE id=? AND framework_revision_id=?').get(sourceId,revisionId))throw failure('NOT_FOUND','node not found');db.prepare('UPDATE knowledge_evidence SET framework_node_id=? WHERE framework_node_id=?').run(targetNodeId,sourceId);db.prepare('UPDATE framework_nodes SET parent_id=? WHERE parent_id=? AND framework_revision_id=?').run(targetNodeId,sourceId,revisionId);db.prepare('DELETE FROM framework_nodes WHERE id=?').run(sourceId);}return db.prepare('SELECT * FROM framework_nodes WHERE id=?').get(targetNodeId);});}
  function evidence({bookId,ownerId,revisionId}){if(!ownedRevision(bookId,ownerId,revisionId))throw failure('NOT_FOUND','framework not found');return db.prepare('SELECT e.* FROM knowledge_evidence e JOIN framework_nodes n ON n.id=e.framework_node_id WHERE n.framework_revision_id=?').all(revisionId);}
  function cloneDraft({bookId,ownerId,revisionId,idempotencyKey}){const source=ownedRevision(bookId,ownerId,revisionId);if(!source)throw failure('NOT_FOUND','framework not found');if(source.status!=='confirmed')throw failure('INVALID_STATE','source not confirmed');const existing=db.prepare('SELECT * FROM framework_revisions WHERE book_id=? AND clone_key=?').get(bookId,idempotencyKey);if(existing)return existing;return transaction(db,()=>{const id=crypto.randomUUID(),now=Date.now(),number=db.prepare('SELECT count(*) n FROM framework_revisions WHERE book_id=?').get(bookId).n+1;db.prepare(`INSERT INTO framework_revisions (id,book_id,book_revision_id,chapter_revision_id,revision_number,status,source_revision_id,clone_key,created_at) VALUES (?,?,?,?,?,'draft',?,?,?)`).run(id,bookId,source.book_revision_id,source.chapter_revision_id,number,revisionId,idempotencyKey,now);const nodes=db.prepare('SELECT * FROM framework_nodes WHERE framework_revision_id=? ORDER BY order_index').all(revisionId),ids=new Map(nodes.map(n=>[n.id,crypto.randomUUID()]));for(const n of nodes)db.prepare(`INSERT INTO framework_nodes (id,framework_revision_id,parent_id,node_type,origin,title,summary,order_index,status,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?, 'draft',?,?,?)`).run(ids.get(n.id),id,n.parent_id?ids.get(n.parent_id):null,n.node_type,n.origin,n.title,n.summary,n.order_index,n.version,now,now);for(const n of nodes)for(const e of db.prepare('SELECT * FROM knowledge_evidence WHERE framework_node_id=?').all(n.id))db.prepare(`INSERT INTO knowledge_evidence (id,framework_node_id,book_revision_id,chapter_id,source_unit_id,locator_json,quote,quote_hash,source_text_hash,is_valid,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(crypto.randomUUID(),ids.get(n.id),e.book_revision_id,e.chapter_id,e.source_unit_id,e.locator_json,e.quote,e.quote_hash,e.source_text_hash,e.is_valid,now);return db.prepare('SELECT * FROM framework_revisions WHERE id=?').get(id);});}
  function validateFrameworkForConfirmation(revisionId){const nodes=db.prepare('SELECT * FROM framework_nodes WHERE framework_revision_id=?').all(revisionId),byId=new Map(nodes.map(n=>[n.id,n])),roots=nodes.filter(n=>!n.parent_id);if(!nodes.length||roots.length!==1)throw failure('FRAMEWORK_QUALITY_FAILED','framework requires one root');for(const node of nodes){if(node.parent_id&&!byId.has(node.parent_id))throw failure('FRAMEWORK_QUALITY_FAILED','framework has orphan node');const seen=new Set([node.id]);let parent=node.parent_id,depth=1;while(parent){if(seen.has(parent)||++depth>5)throw failure('FRAMEWORK_QUALITY_FAILED','framework hierarchy invalid');seen.add(parent);parent=byId.get(parent)?.parent_id;}const evidenceCount=db.prepare('SELECT count(*) n FROM knowledge_evidence WHERE framework_node_id=? AND is_valid=1').get(node.id).n;if(node.origin==='source_claim'&&evidenceCount<1)throw failure('FRAMEWORK_QUALITY_FAILED','source claim requires evidence');if(node.origin==='system_synthesis'){const sources=parse(node.source_node_ids_json,[]);if(!Array.isArray(sources)||new Set(sources).size<2||sources.some(id=>id===node.id||!byId.has(id)))throw failure('FRAMEWORK_QUALITY_FAILED','system synthesis requires two source nodes');}}}
  function confirm({bookId,ownerId,revisionId,idempotencyKey}){const revision=ownedRevision(bookId,ownerId,revisionId);if(!revision)throw failure('NOT_FOUND','framework not found');if(revision.status==='confirmed')return revision;assertDraft(revision);validateFrameworkForConfirmation(revisionId);return transaction(db,()=>{const now=Date.now();db.prepare("UPDATE framework_revisions SET status='confirmed',confirm_key=?,confirmed_at=? WHERE id=? AND status='draft'").run(idempotencyKey,now,revisionId);db.prepare("UPDATE framework_nodes SET status='confirmed' WHERE framework_revision_id=?").run(revisionId);db.prepare("UPDATE books SET active_framework_revision_id=?,status='ready',updated_at=? WHERE id=? AND owner_id=?").run(revisionId,now,bookId,ownerId);if(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='knowledge_vault'").get())for(const n of db.prepare('SELECT * FROM framework_nodes WHERE framework_revision_id=?').all(revisionId))db.prepare(`INSERT OR IGNORE INTO knowledge_vault (id,user_id,type,title,summary,content,source,added_at,tags,extra_json) VALUES (?,?, 'theory',?,?,?,?,?,'[]',?)`).run(`book-framework:${n.id}`,ownerId,n.title,n.summary,n.summary,`book:${bookId}`,now,JSON.stringify({bookId,frameworkRevisionId:revisionId,frameworkNodeId:n.id}));return db.prepare('SELECT * FROM framework_revisions WHERE id=?').get(revisionId);});}

  function chapterInput(chapter, revisionId) {
    const start=parse(chapter.start_locator_json),end=parse(chapter.end_locator_json),startUnit=locatorUnit(start),endUnit=locatorUnit(end);if(startUnit===null||endUnit===null)throw failure('VALIDATION_ERROR','chapter locator invalid');
    const units=db.prepare("SELECT * FROM book_source_units WHERE book_revision_id=? AND status='completed' AND unit_index BETWEEN ? AND ? ORDER BY unit_index").all(revisionId,startUnit,endUnit);if(!units.length)throw failure('VALIDATION_ERROR','chapter source missing');
    const segments=units.map(unit=>{const text=fs.readFileSync(unit.raw_text_path,'utf8');const from=unit.unit_index===startUnit?(start.char??start.charStart??0):0;const to=unit.unit_index===endUnit?(end.char??end.charEnd??text.length-1):text.length-1;return {segmentId:`${chapter.id}:${unit.unit_index}`,sourceUnitId:unit.id,text:text.slice(from,to+1),absoluteBaseOffset:from,allowedAbsoluteStart:from,allowedAbsoluteEnd:to,unitIndex:unit.unit_index,resourcePath:unit.resource_path||null,kind:start.kind||parse(unit.locator_json).kind||'text'};});
    return { text:segments.map(segment=>segment.text).join('\n'), segments };
  }
  function mapEvidence(nodes, segments) { const byId=new Map(segments.map(segment=>[segment.segmentId,segment]));return nodes.map(node=>({...node,evidence:(node.evidence||[]).map(item=>{const segment=byId.get(item.segmentId);if(!segment||item.relativeCharStart<0||item.relativeCharEnd<item.relativeCharStart||item.relativeCharEnd>=segment.text.length)throw failure('EVIDENCE_INVALID','evidence outside segment');return {sourceUnitId:segment.sourceUnitId,locator:{kind:segment.kind,unitIndex:segment.unitIndex,resourcePath:segment.resourcePath||undefined,charStart:segment.absoluteBaseOffset+item.relativeCharStart,charEnd:segment.absoluteBaseOffset+item.relativeCharEnd},quote:item.quote};})})); }
  function readStep(step) { try { const bytes=fs.readFileSync(step.output_path); if(hash(bytes)!==step.output_hash) return null; const result=JSON.parse(bytes); return Array.isArray(result.nodes)?result:null; } catch { return null; } }
  function writeStep(jobId, leaseToken, step, result) { jobs.assertLease(jobId,leaseToken);fs.mkdirSync(outputRoot,{recursive:true});const bytes=Buffer.from(JSON.stringify(result)),file=path.join(outputRoot,`${step.id}.json`),temp=`${file}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(temp,bytes,{flag:'wx'});jobs.assertLease(jobId,leaseToken);fs.renameSync(temp,file);jobs.assertLease(jobId,leaseToken);db.prepare("UPDATE book_job_steps SET status='completed',output_path=?,output_hash=?,attempt_count=attempt_count+1,token_count=?,cost_amount=?,finished_at=? WHERE id=? AND EXISTS (SELECT 1 FROM book_jobs WHERE id=? AND status='running' AND lease_token=? AND lease_expires_at>=? AND cancel_requested_at IS NULL)").run(file,hash(bytes),result.tokenCount,result.costAmount,Date.now(),step.id,jobId,leaseToken,Date.now()); }
  async function processJob({jobId,leaseToken}){const job=db.prepare("SELECT * FROM book_jobs WHERE id=? AND job_type='framework'").get(jobId);if(!job)throw failure('NOT_FOUND','framework job not found');jobs.assertLease(jobId,leaseToken);const chapterRevision=db.prepare("SELECT * FROM chapter_revisions WHERE book_revision_id=(SELECT active_book_revision_id FROM books WHERE id=?) AND status='confirmed' ORDER BY revision_number DESC LIMIT 1").get(job.book_id),chapters=db.prepare('SELECT * FROM book_chapters WHERE chapter_revision_id=? ORDER BY order_index').all(chapterRevision.id),all=[];let runId='',tokens=0,cost=0;
    for(const chapter of chapters){jobs.assertLease(jobId,leaseToken);const inputHash=hash(`${chapter.id}:${chapter.version}`);db.prepare(`INSERT OR IGNORE INTO book_job_steps (id,job_id,chapter_id,step_type,status,input_hash,attempt_count) VALUES (?,?,?,'framework_extract','pending',?,0)`).run(crypto.randomUUID(),jobId,chapter.id,inputHash);const step=db.prepare("SELECT * FROM book_job_steps WHERE job_id=? AND chapter_id=? AND step_type='framework_extract' AND input_hash=?").get(jobId,chapter.id,inputHash);let result=step.status==='completed'?readStep(step):null;
      if(!result){if(step.status==='completed')db.prepare("UPDATE book_job_steps SET status='pending',output_path=NULL,output_hash=NULL WHERE id=?").run(step.id);const input=chapterInput(chapter,chapterRevision.book_revision_id);jobs.assertLease(jobId,leaseToken);try{result=await workflow.runChapter({chapter:{id:chapter.id,title:chapter.title,...input},userId:job.owner_id});jobs.assertLease(jobId,leaseToken);result={...result,nodes:mapEvidence(result.nodes,input.segments)};try{for(const n of result.nodes)for(const e of n.evidence||[])validateEvidence({bookRevisionId:chapterRevision.book_revision_id,sourceUnitId:e.sourceUnitId,locator:e.locator,quote:e.quote,chapter});}catch{result=await workflow.runChapter({chapter:{id:chapter.id,title:chapter.title,...input},userId:job.owner_id,repair:true});jobs.assertLease(jobId,leaseToken);result={...result,nodes:mapEvidence(result.nodes,input.segments)};for(const n of result.nodes)for(const e of n.evidence||[])validateEvidence({bookRevisionId:chapterRevision.book_revision_id,sourceUnitId:e.sourceUnitId,locator:e.locator,quote:e.quote,chapter});}writeStep(jobId,leaseToken,step,result);}catch(error){try{jobs.assertLease(jobId,leaseToken);db.prepare("UPDATE book_job_steps SET status='failed',attempt_count=attempt_count+1,finished_at=? WHERE id=?").run(Date.now(),step.id);}catch{}throw error;}}
      all.push(...result.nodes.map(node=>({...node,evidence:(node.evidence||[]).map(item=>({...item,chapterId:chapter.id}))})));runId=result.runId||runId;tokens+=Number(result.tokenCount||0);cost+=Number(result.costAmount||0);
    }
    jobs.assertLease(jobId,leaseToken);if(all.length===0&&chapters.length)throw failure('FRAMEWORK_INCOMPLETE','chapter outputs incomplete');
    const mergeHash=hash(JSON.stringify(all));db.prepare(`INSERT OR IGNORE INTO book_job_steps (id,job_id,chapter_id,step_type,status,input_hash,attempt_count) VALUES (?,?,NULL,'framework_merge','pending',?,0)`).run(crypto.randomUUID(),jobId,mergeHash);const mergeStep=db.prepare("SELECT * FROM book_job_steps WHERE job_id=? AND step_type='framework_merge' AND input_hash=?").get(jobId,mergeHash);let merged=mergeStep.status==='completed'?readStep(mergeStep):null;
    if(!merged){if(!workflow?.runMerge)throw failure('WORKFLOW_NOT_CONFIGURED','book framework merge workflow is not configured');merged=await workflow.runMerge({nodes:all,userId:job.owner_id});jobs.assertLease(jobId,leaseToken);if(!Array.isArray(merged.nodes)||!merged.nodes.length)throw failure('FRAMEWORK_INCOMPLETE','book merge output incomplete');writeStep(jobId,leaseToken,mergeStep,merged);}
    runId=merged.runId||runId;tokens+=Number(merged.tokenCount||0);cost+=Number(merged.costAmount||0);return seedDraft({bookId:job.book_id,ownerId:job.owner_id,chapterRevisionId:chapterRevision.id,nodes:merged.nodes,runId,tokenCount:tokens,costAmount:cost,jobId,leaseToken});
  }
  return {validateEvidence,seedDraft,list,detail,updateNode,merge,evidence,cloneDraft,confirm,processJob};
}
module.exports={createBookFrameworkService};
