import type { SceneEntry } from './types';

export const ROLE_SWITCH_INSTRUCTION = `你必须同时跟踪多个角色立场：识别盟友与阻力；每轮明确 role_address（当前面向谁说话）；可表现联合施压(joint_pressure)或暗中协助；管理会议节奏（引导、打断、总结、推进）。返回 JSON 须含 role_address、branch_suggestions、difficulty_rating、cultural_signal 及四维 feedback_* 字段。`;

export const THEME_TO_SCENE_MAP: Record<string, string> = {
  '商务谈判：让步与施压': 'scene-1',
  '危机公关：外媒答疑': 'scene-2',
  '项目汇报：跨国董事会': 'scene-5',
};

export const SCENE_DATABASE: SceneEntry[] = [
  // ── 初阶多角色（三方博弈） ──
  {
    id: 'scene-begin-1',
    title: '初阶：项目延期说明会',
    shortTitle: '项目延期说明会',
    tier: '初阶',
    level: 4,
    desc: '客户要求赔偿，上级要求保关系；需在两方之间平衡语气并提出折中方案。',
    roleList: '我(项目负责人) + 外籍总监 + 客户代表',
    allies: [{ name: '外籍总监', label: '盟友', desc: '倾向保关系，暗示可内部消化' }],
    blockers: [{ name: '客户代表', label: '阻力', desc: '要求书面赔偿与 SLA 惩罚条款' }],
    neutrals: [{ name: '项目监理', label: '中立', desc: '只陈述客观延期原因' }],
    conflicts: ['赔偿条款', '关系维护'],
    culturalContext: 'Direct communication expected from client side. 对上级用委婉汇报，对客户需明确底线。',
    openingLine: "We've been waiting forty minutes. Before we discuss recovery plans, I need clarity on who bears the penalty clause.",
  },
  {
    id: 'scene-begin-2',
    title: '初阶：跨部门资源争夺',
    shortTitle: '跨部门资源争夺',
    tier: '初阶',
    level: 4,
    desc: '财务控成本，风控收紧额度；识别盟友并用数据说服。',
    roleList: '我(信贷部) + 财务总监 + 风控总监',
    allies: [{ name: '业务副总', label: '盟友', desc: '支持适度放量以保 KPI' }],
    blockers: [{ name: '财务总监', label: '阻力', desc: '严控成本，要求砍 30% 预算' }, { name: '风控总监', label: '阻力', desc: '收紧授信额度与担保要求' }],
    neutrals: [],
    conflicts: ['预算削减', '授信额度'],
    culturalContext: 'Hierarchy 明显，需先尊重职能边界再提出数据论证。',
    openingLine: 'Finance and Risk have conflicting numbers on this portfolio. Walk us through why your team deserves the headroom.',
  },
  {
    id: 'scene-begin-3',
    title: '初阶：新政策宣贯答疑',
    shortTitle: '新政策宣贯答疑',
    tier: '初阶',
    level: 4,
    desc: '两位下属分别担心执行难与考核变；回应不同顾虑并保持政策一致性。',
    roleList: '我(宣讲人) + 业务线A下属 + 业务线B下属',
    allies: [{ name: '业务线A', label: '盟友', desc: '愿意试点，需资源支持' }],
    blockers: [{ name: '业务线B', label: '阻力', desc: '担心考核指标突变影响团队士气' }],
    neutrals: [],
    conflicts: ['执行难度', '考核调整'],
    culturalContext: '下属期待 Direct 回答但需保留 Hierarchy 分寸，避免公开否定政策。',
    openingLine: "The new KPI framework sounds ambitious on paper, but my team can't see how we hit it without extra headcount.",
  },
  // ── 高阶多角色（四方及以上） ──
  {
    id: 'scene-1',
    title: '高阶：国际银团贷款谈判',
    shortTitle: '国际银团贷款谈判',
    tier: '高阶',
    level: 4,
    desc: '核心争议：利率上浮 0.5% 与抵押物权属争议。借款方资金缺口倒逼 72 小时谈判时限。',
    roleList: '我(牵头行) + 参团行A + 参团行B + 借款企业CFO',
    allies: [{ name: 'CEO', label: '盟友', desc: '极力推动落地，愿让步换时间' }],
    blockers: [{ name: 'CFO', label: '阻力', desc: '严控 IRR 红线，要求重跑估值' }],
    neutrals: [{ name: '监管方', label: '中立', desc: '只关注合规证据与权属文件' }],
    conflicts: ['利率上浮 0.5%', '抵押物权属'],
    culturalContext: '美系主导（Action-oriented, Direct）。切忌过分谦逊，直面利益冲突并明确亮出 Bottom Line。',
    openingLine: "Gentlemen, let's address the rate adjustment first. Our IRR model doesn't absorb another fifty basis points without collateral restructuring.",
  },
  {
    id: 'scene-adv-2',
    title: '高阶：Overseas Project Kick-off',
    shortTitle: '海外项目启动会',
    tier: '高阶',
    level: 5,
    desc: '合规、进度与本地化冲突；跨文化沟通并维护中方利益。',
    roleList: '我(中方负责人) + 当地官员 + 本地伙伴 + 外方工程师',
    allies: [{ name: '本地伙伴', label: '盟友', desc: '熟悉当地流程，可斡旋' }],
    blockers: [{ name: '外方工程师', label: '阻力', desc: '坚持原设计标准，拒绝本地化调整' }],
    neutrals: [{ name: '当地官员', label: '中立', desc: '关注合规许可与社区关系' }],
    conflicts: ['合规许可', '本地化标准'],
    culturalContext: 'Direct vs 委婉并存：官员表述间接，工程师 Direct。需分别调整语气。',
    openingLine: 'Before we sign off the timeline, the local regulator expects explicit ESG commitments in the contract appendix.',
  },
  {
    id: 'scene-adv-3',
    title: '高阶：内部晋升评审会',
    shortTitle: '内部晋升评审会',
    tier: '高阶',
    level: 5,
    desc: '评委关注点各异（能力/业绩/成本）；依次回答且不得罪人。',
    roleList: '我(候选人) + 外籍HR总监 + 业务负责人 + 财务代表',
    allies: [{ name: '业务负责人', label: '盟友', desc: '认可业绩，愿背书' }],
    blockers: [{ name: '财务代表', label: '阻力', desc: '质疑成本管控与 ROI 贡献' }],
    neutrals: [{ name: '外籍HR总监', label: '中立', desc: '关注领导力与文化 fit' }],
    conflicts: ['业绩证明', '成本管控'],
    culturalContext: '欧美 HR Direct 提问，亚洲业务方更委婉。需切换 register。',
    openingLine: "Let's start with your P&L ownership. Finance flagged a 12% overspend in Q3—how do you reconcile that with a promotion case?",
  },
  {
    id: 'scene-2',
    title: '高阶：危机公关媒体发布会',
    shortTitle: '危机公关媒体会',
    tier: '高阶',
    level: 5,
    desc: '面对尖锐、陷阱与情绪化提问，用英语冷静应对并转向正面。',
    roleList: '我(发言人) + 记者A + 记者B + 在线观众',
    allies: [{ name: '公关总监', label: '盟友', desc: '试图用技术性误差推锅给第三方' }],
    blockers: [{ name: '记者A', label: '阻力', desc: '掌握邮件截图，紧逼决策链' }, { name: '记者B', label: '阻力', desc: '情绪化追问高管责任' }],
    neutrals: [{ name: '法务官', label: '中立', desc: '警告承认将触发天价罚款' }],
    conflicts: ['数据造假责任', '披露边界'],
    culturalContext: '欧系合规文化（Regulation-first）。强调程序正义与透明度。',
    openingLine: 'We have evidence your subsidiary manipulated environmental data. Did the board know before the IPO prospectus went out?',
  },
  // ── 跨文化专项 ──
  {
    id: 'scene-culture-1',
    title: '跨文化：中日韩三方会议',
    shortTitle: '中日韩三方会议',
    tier: '跨文化',
    level: 4,
    desc: '日方委婉、韩方直接；识别不同文化表达习惯，不做错误假设。',
    roleList: '我(中国方) + 日本客户 + 韩国供应商',
    allies: [{ name: '韩国供应商', label: '盟友', desc: 'Direct 支持交期，愿共担成本' }],
    blockers: [{ name: '日本客户', label: '阻力', desc: '委婉表达对质量顾虑，不直接说 NO' }],
    neutrals: [],
    conflicts: ['质量标准', '交期承诺'],
    culturalContext: '日方 High-context 委婉；韩方 Low-context Direct。勿将沉默当同意。',
    openingLine: 'It might be... somewhat challenging to accept the current spec as-is. We would need to consider alternatives carefully.',
  },
  {
    id: 'scene-culture-2',
    title: '跨文化：欧美非视频会',
    shortTitle: '欧美非视频会',
    tier: '跨文化',
    level: 4,
    desc: '克服时差与沟通效率问题，用简单英语确保理解并确认共识。',
    roleList: '我(亚洲总部) + 美国团队 + 非洲当地经理',
    allies: [{ name: '非洲经理', label: '盟友', desc: '熟悉本地运营，需清晰指令' }],
    blockers: [{ name: '美国团队', label: '阻力', desc: '质疑远程决策效率' }],
    neutrals: [],
    conflicts: ['时差协调', '决策效率'],
    culturalContext: '美国 Direct、非洲关系导向。用简单句确认共识，避免 idioms。',
    openingLine: "We're three hours into this call and still don't have a decision owner. Can we lock action items before everyone drops?",
  },
  {
    id: 'scene-3',
    title: '跨文化：中东商务晚宴',
    shortTitle: '中东商务晚宴',
    tier: '跨文化',
    level: 4,
    desc: '宗教礼仪、等级观念与非正式谈判；运用高阶英语社交话术。',
    roleList: '我 + 当地亲王 + 欧美顾问',
    allies: [{ name: '投资总监', label: '盟友', desc: '用家族荣誉包装强制回购条款' }],
    blockers: [{ name: '战略负责人', label: '阻力', desc: '担心 ESG 违规，私下施压' }],
    neutrals: [{ name: '王室合伙人', label: '中立', desc: '暗示宗教禁忌与政商潜规则' }],
    conflicts: ['对赌回购条款', 'ESG 披露'],
    culturalContext: '中东政商文化（Relationship & Hierarchy）。重视关系与家族荣誉，避免当众逼迫对方妥协。',
    openingLine: 'Over coffee, my colleague mentioned the buyback clause might touch on sensitive ownership structures. Perhaps we explore a softer formulation?',
  },
  // ── 高级定制追加 ──
  {
    id: 'scene-custom-1',
    title: '定制：政策性银行三方融资会',
    shortTitle: '三方基础设施融资',
    tier: '定制',
    level: 5,
    desc: '政策性银行 + 外资金融机构 + 地方政府三方基础设施融资会议。',
    roleList: '我(牵头) + 政策性银行 + 外资金融机构 + 地方政府',
    allies: [{ name: '政策性银行', label: '盟友', desc: '愿提供低成本长期资金' }],
    blockers: [{ name: '外资金融机构', label: '阻力', desc: '要求商业条款与政府隐性担保' }],
    neutrals: [{ name: '地方政府', label: '中立', desc: '关注就业与合规审批' }],
    conflicts: ['担保结构', '提款条件'],
    culturalContext: '政府 Hierarchy 高；外资 Direct 要求 transparency；需双语 register 切换。',
    openingLine: 'The offshore lender wants explicit sovereign comfort language. Policy bank needs to stay within regulatory guidance—where is the middle ground?',
  },
  {
    id: 'scene-custom-2',
    title: '定制：海外并购整合会',
    shortTitle: '海外并购整合会',
    tier: '定制',
    level: 5,
    desc: '买方代表 + 被收购方原CEO + 外籍法律顾问 + 员工代表四方博弈。',
    roleList: '我(买方) + 原CEO + 外籍法律顾问 + 员工代表',
    allies: [{ name: '投行 FA', label: '中立', desc: '找价差空间，靠佣金驱动防破裂' }],
    blockers: [{ name: '原CEO', label: '阻力', desc: '以协同溢价模糊财务缺口' }],
    neutrals: [{ name: '员工代表', label: '中立', desc: '关注裁员与文化冲突' }],
    conflicts: ['4700万诉讼', '人员整合'],
    culturalContext: '英系保守主义（Risk-averse）。极端注重细节与免责声明。',
    openingLine: 'Employee council submitted questions on retention packages. Legal wants indemnities signed before we discuss synergy targets.',
  },
  {
    id: 'scene-custom-3',
    title: '定制：跨境合规检查',
    shortTitle: '跨境合规检查',
    tier: '定制',
    level: 5,
    desc: '监管官员 + 我 + 外籍审计师三方合规对话。',
    roleList: '我 + 监管官员 + 外籍审计师',
    allies: [{ name: '内审总监', label: '盟友', desc: '已准备整改路线图' }],
    blockers: [{ name: '监管官员', label: '阻力', desc: '质疑数据跨境传输合规' }],
    neutrals: [{ name: '外籍审计师', label: '中立', desc: '按 IFRS 标准客观陈述' }],
    conflicts: ['数据跨境', '审计意见'],
    culturalContext: 'Regulation-first，官员表述正式；审计师 Direct 引用条文。',
    openingLine: 'Our inspection note cites gaps in cross-border data mapping. Please walk us through your Article 28 equivalent safeguards.',
  },
  {
    id: 'scene-custom-4',
    title: '定制：国际行业峰会 Q&A',
    shortTitle: '国际行业峰会',
    tier: '定制',
    level: 5,
    desc: '作为演讲者面对台下多角色切换提问。',
    roleList: '我(演讲者) + 投资者 + 竞争对手 + 媒体记者',
    allies: [{ name: '行业分析师', label: '盟友', desc: '抛出友好问题帮铺垫' }],
    blockers: [{ name: '竞争对手', label: '阻力', desc: '尖锐质疑技术路线' }, { name: '媒体记者', label: '阻力', desc: '陷阱式提问' }],
    neutrals: [{ name: '投资者', label: '中立', desc: '关注 ROI 与 risk' }],
    conflicts: ['技术路线', '估值预期'],
    culturalContext: '欧美峰会 Direct Q&A；需快速切换对象并保持风度。',
    openingLine: 'Your slide showed 40% cost reduction, but our due diligence suggests the baseline was inflated. How do you respond?',
  },
  {
    id: 'scene-custom-5',
    title: '定制：远程团队管理',
    shortTitle: '远程团队管理',
    tier: '定制',
    level: 4,
    desc: '东南亚下属 + 东欧技术主管 + 美国产品经理跨时区协调。',
    roleList: '我 + 东南亚下属 + 东欧技术主管 + 美国产品经理',
    allies: [{ name: '东南亚下属', label: '盟友', desc: '执行力强，需清晰 deadline' }],
    blockers: [{ name: '美国产品经理', label: '阻力', desc: '频繁变更需求' }],
    neutrals: [{ name: '东欧技术主管', label: '中立', desc: '关注架构稳定与文档' }],
    conflicts: ['需求变更', '交付节奏'],
    culturalContext: '美国 Direct feedback；东南亚 High-context；东欧注重流程与文档。',
    openingLine: "Product pushed another scope change at midnight our time. Engineering in Warsaw wasn't consulted—this can't be the norm.",
  },
  // ── 保留经典场景 ──
  {
    id: 'scene-4',
    title: '高阶：跨国并购尽调对话',
    shortTitle: '跨国并购尽调',
    tier: '高阶',
    level: 5,
    desc: '发现标的方隐瞒 4700 万美元专利诉讼，高压博弈估值调整。',
    roleList: '我(买方) + 投行FA + 标的CEO + 买方CFO',
    allies: [{ name: '投行 FA', label: '中立', desc: '找价差空间，靠佣金驱动防破裂' }],
    blockers: [{ name: '标的 CEO', label: '阻力', desc: '以协同溢价模糊财务缺口' }],
    neutrals: [{ name: '买方 CFO', label: '对立', desc: '要求拆分财务，隔离争议资产' }],
    conflicts: ['4700万诉讼', '估值下调'],
    culturalContext: '英系保守主义（Risk-averse）。极端注重细节与免责声明。',
    openingLine: 'We found an undisclosed patent suit worth forty-seven million. Your synergy deck assumes zero litigation reserve—that needs revisiting.',
  },
  {
    id: 'scene-5',
    title: '高阶：董事会战略否决博弈',
    shortTitle: '董事会战略否决',
    tier: '高阶',
    level: 5,
    desc: 'CEO 提案 6 亿美元出海战略，遭大股东联合否决，独立董事成关键票。',
    roleList: '我(CEO团队) + 创始人CEO + 大股东 + 独立董事',
    allies: [{ name: '创始人 CEO', label: '盟友', desc: '诉诸竞争威胁，争情感逻辑双支持' }],
    blockers: [{ name: '大股东', label: '阻力', desc: '死守 ROE 红线，欲换血管理层' }],
    neutrals: [{ name: '独立董事', label: '关键', desc: '只看程序合规与受托责任边界' }],
    conflicts: ['6亿预算', '管理权争夺'],
    culturalContext: '多边复合博弈（Consensus-building）。需识别中、美、欧不同利益方诉求。',
    openingLine: 'Major shareholders reject the six-billion overseas plan unless ROE targets are guaranteed. Independent directors want a fiduciary memo first.',
  },
];

