import { useState } from 'react';
import { confirmBookChapters, confirmFramework, getFramework, listBookChapters, listFrameworks, updateBookChapter, updateFrameworkNode, type BookChapter, type FrameworkNode } from '../../services/bookManagementAPI';

export default function BookWorkflowPanel({ bookId }: { bookId: string }) {
  const [chapters, setChapters] = useState<BookChapter[]>([]); const [nodes, setNodes] = useState<FrameworkNode[]>([]); const [revisionId, setRevisionId] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { setBusy(true); setError(''); try { const list = await listBookChapters(bookId); setChapters(list); const draft = (await listFrameworks(bookId)).find((item) => item.status === 'draft'); if (draft) { setRevisionId(draft.id); setNodes((await getFramework(bookId, draft.id)).nodes); } } catch (cause) { setError(cause instanceof Error ? cause.message : '加载失败'); } finally { setBusy(false); } };
  const confirmChapters = async () => { setBusy(true); try { const drafts = chapters.filter((item) => item.status === 'draft'); await Promise.all(drafts.map((chapter) => updateBookChapter(bookId, chapter))); const draftRevisionId = drafts[0]?.chapter_revision_id; const result = await confirmBookChapters(bookId, draftRevisionId); window.dispatchEvent(new CustomEvent('open-book-job', { detail: { bookId, jobId: result.frameworkJob.id } })); } catch (cause) { setError(cause instanceof Error ? cause.message : '确认失败'); } finally { setBusy(false); } };
  return <section className="space-y-3 rounded-xl border border-slate-200 p-3"><button type="button" disabled={busy} onClick={load} className="rounded-lg border px-3 py-2 text-xs font-bold">{busy ? '加载中…' : '管理章节与框架草稿'}</button>
    {chapters.some((item) => item.status === 'draft') && <div className="space-y-2"><h3 className="text-xs font-black">确认章节</h3>{chapters.filter((item) => item.status === 'draft').map((chapter, index) => <div key={chapter.id} className="grid grid-cols-[1fr_4rem_auto] gap-2"><input aria-label={`章节 ${index + 1} 标题`} value={chapter.title} onChange={(e) => setChapters((all) => all.map((item) => item.id === chapter.id ? { ...item, title: e.target.value } : item))} className="rounded border p-1 text-xs" /><input aria-label={`章节 ${index + 1} 层级`} type="number" min="1" max="5" value={chapter.level} onChange={(e) => setChapters((all) => all.map((item) => item.id === chapter.id ? { ...item, level: Number(e.target.value) } : item))} className="rounded border p-1 text-xs" /><button onClick={async () => { const saved = await updateBookChapter(bookId, chapter); setChapters((all) => all.map((item) => item.id === saved.id ? saved : item)); }} className="text-xs text-indigo-700">保存</button></div>)}<button onClick={confirmChapters} className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">确认章节并生成框架</button></div>}
    {revisionId && <div className="space-y-2"><h3 className="text-xs font-black">框架草稿</h3>{nodes.map((node) => <div key={node.id} className="space-y-1 rounded border p-2"><input value={node.title} onChange={(e) => setNodes((all) => all.map((item) => item.id === node.id ? { ...item, title: e.target.value } : item))} className="w-full rounded border p-1 text-xs" /><textarea value={node.summary} onChange={(e) => setNodes((all) => all.map((item) => item.id === node.id ? { ...item, summary: e.target.value } : item))} className="w-full rounded border p-1 text-xs" /><button onClick={async () => { const saved = await updateFrameworkNode(bookId, revisionId, node); setNodes((all) => all.map((item) => item.id === saved.id ? saved : item)); }} className="text-xs text-indigo-700">保存节点</button></div>)}<button onClick={async () => { try { await confirmFramework(bookId, revisionId); location.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : '框架质量未通过'); } }} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">确认并发布框架</button></div>}
    {error && <p role="alert" className="text-xs text-rose-600">{error}</p>}</section>;
}
