const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');

const server = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');
const service = fs.readFileSync(path.join(__dirname, '..', 'services', 'freeOralSessions.js'), 'utf8');
const rootPackage = JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'package.json'), 'utf8'));

assert.match(server, /initFreeOralTables\(db\)/, '服务启动时应初始化自由口语表');
assert.match(server, /app\.get\('\/api\/english\/free-oral\/sessions'/, '应提供会话列表');
assert.match(server, /app\.post\('\/api\/english\/free-oral\/sessions'/, '应提供新建会话');
assert.match(server, /app\.get\('\/api\/english\/free-oral\/sessions\/:sessionId'/, '应提供会话详情');
assert.match(server, /app\.patch\('\/api\/english\/free-oral\/sessions\/:sessionId'/, '应提供主题和 Dify conversation_id 更新');
assert.match(server, /app\.post\('\/api\/english\/free-oral\/sessions\/:sessionId\/messages'/, '应保留系统事件消息持久化');
assert.match(server, /app\.post\('\/api\/english\/oral\/free-sessions\/:sessionId\/messages'/, '应提供服务端统一发送接口');
assert.match(server, /executeFreeOralTurn/, '统一发送接口必须编排持久化与 Dify 调用');
assert.match(server, /clientMessageId/, '统一发送必须使用客户端幂等键');
assert.match(server, /AbortSignal\.timeout\(30000\)/, '独立 Dify 请求必须设置超时');
assert.match(server, /error\.code = data\.code/, 'Dify 错误码必须传给会话恢复判断');
assert.match(server, /checkFreeOralRateLimit\(userId\)/, '统一发送必须按用户限流');
assert.match(server, /FREE_ORAL_RATE_LIMITED/, '本地限流必须返回稳定错误码');
assert.match(server, /Retry-After/, '本地限流必须告知重试时间');
assert.match(server, /const requestId = crypto\.randomUUID\(\)/, '统一发送必须生成请求追踪 ID');
assert.match(server, /X-Request-Id/, '统一发送响应必须携带请求追踪头');
assert.match(server, /\[自由口语\]\[turn\]/, '统一发送必须记录结构化结果日志');
assert.match(server, /durationMs/, '结构化日志必须记录总耗时');
assert.match(server, /recovered: Boolean\(result\.recovered\)/, '结构化日志必须记录恢复状态');
assert.doesNotMatch(server, /console\.(?:info|warn)\('\[自由口语\]\[turn\]'[^;]*\bcontent\b/, '结构化日志不得记录消息正文');
assert.match(server, /app\.delete\('\/api\/english\/free-oral\/sessions\/:sessionId'/, '应提供删除会话');
assert.match(server, /normalizeFreeOralUserId/, '接口必须归一化 userId');
assert.match(server, /appMode\s*=\s*'sandbox'/, 'Dify 对话代理应区分沙盘与自由对话应用');
assert.match(server, /DIFY_FREE_ORAL_API_KEY/, '自由对话必须使用独立 Dify API Key');
assert.match(server, /appMode\s*===\s*'free-oral'/, '自由对话必须显式路由到独立 Dify 应用');
assert.match(server, /focus_topic/, '自由对话代理必须向 Dify 传递 focus_topic');
assert.match(service, /WHERE id = \? AND user_id = \?/, '详情与更新必须按用户隔离');
assert.match(service, /WHERE session_id = \? AND user_id = \?/, '消息必须按用户和会话隔离');
assert.equal(typeof rootPackage.scripts['verify:free-oral'], 'string', '根项目必须提供单命令发布门禁');
assert.match(rootPackage.scripts['verify:free-oral'], /freeOralSessions\.test\.js/, '门禁必须运行会话测试');
assert.match(rootPackage.scripts['verify:free-oral'], /freeOralTurn\.test\.js/, '门禁必须运行发送测试');
assert.match(rootPackage.scripts['verify:free-oral'], /freeOralRateLimit\.test\.js/, '门禁必须运行限流测试');
assert.match(rootPackage.scripts['verify:free-oral'], /freeOralApiContract\.test\.js/, '门禁必须运行 API 契约');
assert.match(rootPackage.scripts['verify:free-oral'], /freeOralFrontendContract\.test\.js/, '门禁必须运行前端契约');
assert.match(rootPackage.scripts['verify:free-oral'], /npm run lint/, '门禁必须运行 TypeScript 检查');
assert.match(rootPackage.scripts['verify:free-oral'], /npm run build/, '门禁必须运行生产构建');
console.log('freeOralApiContract tests passed');
