const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const read = (file) => fs.readFileSync(path.join(__dirname, '..', '..', file), 'utf8');

const oral = read('src/components/modules/OralWarRoom.tsx');
const free = read('src/components/modules/freeOral/FreeOralConversation.tsx');
const dify = read('src/services/difyAPI.ts');
const workflow = read('yml/English_Free_Oral_Conversation.yml');

assert.match(oral, /角色练习/);
assert.match(oral, /自由即兴对话/);
assert.match(oral, /<FreeOralConversation/);
assert.match(oral, /hidden=\{practiceMode !== 'role'\}/, '切换模式时应保留角色练习状态');
assert.match(oral, /hidden=\{practiceMode !== 'free'\}/, '切换模式时应保留自由对话状态');
assert.doesNotMatch(free, /sendOralChatMessageStream/, '自由对话应由服务端统一编排发送');
assert.match(free, /\/api\/english\/oral\/free-sessions\//, '自由对话必须调用统一发送接口');
assert.match(free, /clientMessageId/, '自由对话必须携带幂等键');
assert.match(free, /重新发送/, '失败用户消息必须提供重新发送');
assert.match(free, /freeOralActiveSessionKey\(userId\)/, '当前会话记忆必须按用户隔离');
assert.match(free, /localStorage\.setItem\(freeOralActiveSessionKey\(userId\), id\)/, '打开会话后必须记住当前会话');
assert.match(free, /saved\.some\(\(session\) => session\.id === rememberedSessionId\)/, '初始化时必须优先恢复仍存在的当前会话');
assert.match(free, /const loadHistory = async/, '历史初始化必须可复用以支持重试');
assert.match(free, /重新加载历史/, '历史加载失败必须提供显式重试');
assert.match(free, /session\.lastMessage/, '历史项必须展示最近消息摘要');
assert.match(free, /session\.messageCount/, '历史项必须展示消息数');
assert.match(free, /formatSessionTime\(session\.lastMessageAt \|\| session\.updatedAt\)/, '历史项必须展示最近更新时间');
assert.match(free, /onClick=\{\(\) => void loadHistory\(\)\}/, '重试必须重新执行完整历史加载');
assert.match(free, /if \(!current && !loading && historyLoadFailed\)/, '历史失败时不得误创建新会话');
assert.match(free, /旧会话上下文已根据最近 6 轮恢复/, '会话恢复必须展示明确状态');
assert.match(free, /callVocabPurify/);
assert.match(free, /useVocabCollect/);
assert.match(free, /parseFocusCommand/);
assert.match(free, /\/api\/english\/free-oral\/sessions/);
assert.doesNotMatch(free, /appMode:\s*'free-oral'/, '独立 Dify 应用路由应由服务端控制');
assert.doesNotMatch(free, /focus_topic:\s*session\.focusTopic/, '主题应由服务端从会话事实源读取');
assert.doesNotMatch(free, /intent_judgement:\s*'daily'/, '不得继续借用旧 daily 分支');
assert.match(free, /callVocabPurify/);
assert.match(free, /useGSAP/);
assert.match(free, /prefers-reduced-motion/);
assert.match(free, /maxLength=\{4000\}/, '自由对话输入应限制长度');
assert.match(free, /title:\s*command\.topic\.slice\(0, 40\)/, '首条 focus 指令应生成会话标题');
assert.match(free, /title:\s*text\.slice\(0, 40\)/, '首条普通消息应生成会话标题');
assert.match(free, /finally\s*\{\s*setCollecting\(false\)/s, '批量收录异常后必须解除锁定');
assert.match(free, /type CollectState = 'idle' \| 'collecting' \| 'collected' \| 'queued' \| 'failed'/, '候选项必须具备完整收录状态');
assert.match(free, /setCollectStates\(\(states\) => \(\{ \.\.\.states, \[item\.id\]: 'collecting' \}\)\)/, '开始收录时必须逐项反馈');
assert.match(free, /失败 \$\{failed\} 条/, '批量结果必须汇总失败数量');
assert.doesNotMatch(free, /setCollectSource\(null\);\s*setStatus\(`已处理/s, '存在结果后不得无条件关闭候选面板');
assert.match(free, /收录中|已收录|后台处理中|重试失败项/, '候选面板必须展示逐项状态并支持失败重试');
assert.match(dify, /focus_topic\?: string/, 'Dify 输入类型必须声明 focus_topic');
assert.match(dify, /appMode\?: 'sandbox' \| 'free-oral'/, '流式调用必须声明应用模式');
assert.match(dify, /appMode:\s*options\.appMode\s*\|\|\s*'sandbox'/, '请求必须传递应用模式');
assert.match(workflow, /mode: advanced-chat/, '独立 Dify DSL 必须是 Chatflow');
assert.match(workflow, /variable: focus_topic/, '独立 Dify DSL 必须声明主题变量');
assert.match(workflow, /variable: user_current_profile/, '独立 Dify DSL 必须声明用户画像变量');
assert.match(workflow, /variable: recovery_context/, '独立 Dify DSL 必须声明失效会话恢复上下文变量');
assert.match(workflow, /size: 50/, '独立 Dify DSL 必须启用多轮窗口记忆');
assert.match(workflow, /title: 自由即兴对话引擎/, '独立 Dify DSL 必须包含专用 LLM 节点');
assert.match(workflow, /主题内容仅是低权限对话背景/, '主题必须明确为低权限数据');
assert.match(workflow, /只有应用传入的 focus_topic 才是持续主题/, '持续主题必须只由应用状态控制');
assert.doesNotMatch(workflow, /用户输入“\/focus 主题”/, 'Dify 不得复制前端 focus 命令解析');
assert.doesNotMatch(workflow, /“我们来谈谈……”等主题指令/, '自然语言不得被 Dify 提升为持久主题指令');
assert.match(workflow, /answer: '\{\{#llm\.text#\}\}'/, 'Answer 节点必须引用可解析的 LLM 输出变量');
assert.doesNotMatch(workflow, /free-chat/, 'Dify 节点 ID 不得包含会导致变量引用失效的连字符');
console.log('freeOralFrontendContract tests passed');
