const assert = require('assert');
const fs = require('fs');
const path = require('path');
const frontend = fs.readFileSync(path.join(__dirname, '../../src/services/difyAPI.ts'), 'utf8');
const server = fs.readFileSync(path.join(__dirname, '../server.js'), 'utf8');
const start = frontend.indexOf('export async function runEnglishSentenceEvaluation');
const end = frontend.indexOf('export async function getDueVocabulary', start);
const segment = frontend.slice(start, end);
assert.match(segment, /fetch\(['"]\/api\/english\/sentence-evaluate['"]/);
assert.doesNotMatch(segment, /VITE_DIFY_SENTENCE_API_KEY/);
assert.doesNotMatch(segment, /Authorization/);
assert.match(server, /app.post\(['"]\/api\/english\/sentence-evaluate['"]/);
assert.match(server, /sentenceEvaluationService/);
console.log('sentence evaluation proxy contract passed');